name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    paths-ignore:
      - doc/**
      - LICENSE
      - README.md

permissions:
  contents: read

jobs:
  test-on-vim:
    name: Vim ${{ matrix.vim_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        vim_version:
          - v9.1.1500
          - v9.2.0000
          - head

        download:
          - available

    uses: mityu/workflow-run-vim-themis/.github/workflows/run-themis.yml@5be69f9736eda162c6933f05a378c10b8a532fb7 # v20260626
    with:
      vim_type: vim
      vim_version: ${{ matrix.vim_version }}
      os: ${{ matrix.os }}
      download: ${{ matrix.download }}

  test-on-neovim:
    name: Neovim ${{ matrix.vim_version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

        vim_version:
          - v0.12.0
          - head

        download:
          - available

    uses: mityu/workflow-run-vim-themis/.github/workflows/run-themis.yml@5be69f9736eda162c6933f05a378c10b8a532fb7 # v20260626
    with:
      vim_type: neovim
      vim_version: ${{ matrix.vim_version }}
      os: ${{ matrix.os }}
      download: ${{ matrix.download }}
